---
title: "Petikan Kandungan Media"
author: "BSPP Gerak Saraf, Tim ICT BPA-JRP"
date: '`r format(Sys.time(), "%B %d, %Y, %H:%M")`'
output:
  html_document: 
    fig_height: 3.5
    fig_width: 5.5
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = NA, echo = FALSE)
options(
  knitr.kable.NA = '',
  knitr.table.format = "html",
  figcap.prefix = "Rajah", figcap.sep = ":",
  figcap.prefix.highlight = "**",
  tabcap.prefix = "Jadual", tabcap.sep = ":",
  tabcap.prefix.highlight = "**"
  ) 
```
```{r initialise, include=FALSE}

library(dplyr)
library(knitr)
library(kableExtra)
library(stringr)

load("daily.RData")
load("newsdaily.RData") # news.today from newsdailyBat.R
options(digits=3)

```
```{r definition, include=FALSE}
def.key <-
  c(
    "esscom", "rentas sempadan",
    "laut China selatan", "krisis di wilayah",
    "antikeganasan", "border",
    "south china sea",
    "southern philippine", "militan", "militant",
    "threat of militant", "sayyaf",
    "Moro ", "southern thailand",
    "islamic state", "overlapping claimt",
    "militant arrested", "malaysia-thailand",
    "malaysia-indonesia", "malaysia-Filipina",
    "daesh"
  )

crime.key <- c( "bomb ", "bom ",
    "culik",  "kidnap",  "rusuh",  "robber",  "rompak",
    "leweng",  "felon",  "senjata",  "violen",
    "suicide",  "bribe",  "rasuah",  "ditahan",
    "fraud" ,  "sprm",  "macc",  "detain",  "misappropriation")

imigr.key <- c("eludup", "rentas", "sempadan", "cross border", "confiscate",
               "imigresen", "immigrant", "rampas")

atm.key <- c("angkatan tentera", "panglima", " atm ", "komander",
             "armed forces", " army", " navy ", "air force", "hishammuddin hussein",
             "tentera darat", "tentera laut", "tentera udara", "unifil",
             "military", "soldier ", "rank and file", "regiment", "bekas tentera",
             "brigade", "briged", "malbatt", "menteri pertahanan",
             "perajurit", "pvatm", "bekas anggota tentera")

pol.key <- c(" bn ", "umno", "Parti Islam Se-Malaysia", " mca ", " pakatan harapan ",
             " mic ", "parti keadilan", "democratic action party", "Parti Pribumi Bersatu Malaysia",
             "parti gerakan", " myppp ", " pbb ", " supp ", " pbs ",
             " pbrs ", " upko ", " spdp ", " prs ", " pcm ",
             "parti amanah nasional", " parlimen ", "hindraf")

pru.key <- c( "pilihan raya", "suruhanjaya pilihanraya", "pru", "daftar pemilih",
              "dewan undangan", "parlimen", "voter", "election commission",
              "general election", "undi pos", "postal vote")


disaster.key <- c("banjir kilat", "flash flood", " fire", "kebakaran", "anging kencang",
                  "tanah runtuh", "land slide", "heavy rain", "strong wind",
                  "oil spill", "tumpahan minyak", "collide")

def.txt <- news.today %>%
  mutate(text = paste(src, "**", headlines, "**",
                      strtrim(article, 650),"... lagi >>", newslink, sep=":")) %>% 
  filter(str_detect(article, paste(def.key, collapse = '|' ))) %>% 
  select(text)

crime.txt <- news.today %>%
  mutate(text = paste(src, "**", headlines, "**",
                      strtrim(article, 650),"... lagi >>", newslink, sep=":")) %>% 
  filter(str_detect(article, paste(crime.key, collapse = '|' ))) %>% 
  select(text)

imigr.txt <- news.today %>%
  mutate(text = paste(src, "**", headlines, "**",
                      strtrim(article, 650),"... lagi >>", newslink, sep=":")) %>% 
  filter(str_detect(article, paste(imigr.key, collapse = '|' ))) %>% 
  select(text)

atm.txt <- news.today %>%
  mutate(text = paste(src, "**", headlines, "**",
                      strtrim(article, 650),"... lagi >>", newslink, sep=":")) %>% 
  filter(str_detect(article, paste(atm.key, collapse = '|' ))) %>% 
  select(text)

pol.txt <- news.today %>%
  mutate(text = paste(src, "**", headlines, "**",
                      strtrim(article, 650),"... lagi >>", newslink, sep=":")) %>% 
  filter(str_detect(article, paste(pol.key, collapse = '|' ))) %>% 
  select(text)

pru.txt <- news.today %>%
  mutate(text = paste(src, "**", headlines, "**",
                      strtrim(article, 650),"... lagi >>", newslink, sep=":")) %>% 
  filter(str_detect(article, paste(pru.key, collapse = '|' ))) %>% 
  select(text)

disaster.txt <- news.today %>%
  mutate(text = paste(src, "**", headlines, "**",
                      strtrim(article, 650),"... lagi >>", newslink, sep=":")) %>% 
  filter(str_detect(article, paste(disaster.key, collapse = '|' ))) %>% 
  select(text)

tbl.tmp <- rbind(def.txt, crime.txt, imigr.txt, atm.txt, pol.txt, pru.txt, disaster.txt)

article.comb <- unique(tbl.tmp)

# filter only current news

article.comb <- article.comb %>%
  anti_join(article.done)

if (daily.run) {
  daily.run <- FALSE
  article.done <- rbind(article.comb, article.done)
  save(file="daily.RData", article.done, kpi.data, daily.run)
}
```

# Artikel

1. **Keselamatan: Dalam Negeri dan Serantau**

```{r keselamatan, echo=FALSE, message=FALSE, warning=FALSE}

article.comb %>%
  filter(str_detect(text, paste(def.key, collapse = '|' ))) %>% 
  select(text) %>%
  kable(col.names = "") %>% 
  kable_styling(
    bootstrap_options = c("striped", "hover"),
    full_width = F,
    position = "left"
  )
```

**a. Jenayah**

```{r jenayah, echo=FALSE, message=FALSE, warning=FALSE}

# remove duplicate
article.comb <- article.comb %>%
  anti_join(def.txt)

article.comb %>%
  filter(str_detect(text, paste(crime.key, collapse = '|' ))) %>% 
  select(text) %>%
  kable(col.names = "") %>% 
  kable_styling(
    bootstrap_options = c("striped", "hover"),
    full_width = F,
    position = "left"
  )

```
**b. Rentas Sempadan**

```{r imigran, echo=FALSE, message=FALSE, warning=FALSE}

article.comb <- article.comb %>%
  anti_join(crime.txt)

article.comb %>%
  filter(str_detect(text, paste(imigr.key, collapse = '|' ))) %>% 
  select(text) %>%
  kable(col.names = "") %>% 
  kable_styling(
    bootstrap_options = c("striped", "hover"),
    full_width = F,
    position = "left"
  )
```

2. **Ketenteraan**

```{r atm, echo=FALSE, message=FALSE, warning=FALSE}

# remove duplicate

article.comb <- article.comb %>%
  anti_join(imigr.txt)

article.comb %>%
  filter(str_detect(text, paste(atm.key, collapse = '|' ))) %>%  
  select(text) %>%
  kable(col.names = "") %>% 
  kable_styling(
    bootstrap_options = c("striped", "hover"),
    full_width = F,
    position = "left"
  )

```

3. **Politik**

a. **Hal-ehwal Parti**

```{r politik, echo=FALSE, message=FALSE, warning=FALSE}

article.comb <- article.comb %>%
  anti_join(atm.txt)

article.comb %>%
  filter(str_detect(text, paste(pol.key, collapse = '|' ))) %>%  
  select(text) %>%
  kable(col.names = "") %>% 
  kable_styling(
    bootstrap_options = c("striped", "hover"),
    full_width = F,
    position = "left"
  )
```
b. **Pilihanraya**

```{r pru, echo=FALSE, message=FALSE, warning=FALSE}

article.comb <- article.comb %>%
  anti_join(pol.txt)

article.comb %>%
  filter(str_detect(text, paste(pru.key, collapse = '|' ))) %>%  
  select(text) %>%
  kable(col.names = "") %>% 
  kable_styling(
    bootstrap_options = c("striped", "hover"),
    full_width = F,
    position = "left"
  )
```

4. **Bencana**

```{r bencana, echo=FALSE, message=FALSE, warning=FALSE}

article.comb <- article.comb %>%
  anti_join(pol.txt)

article.comb %>%
  filter(str_detect(text, paste(disaster.key, collapse = '|' ))) %>%  
  select(text) %>%
  kable(col.names = "") %>% 
  kable_styling(
    bootstrap_options = c("striped", "hover"),
    full_width = F,
    position = "left"
  )
```